apiVersion: v1
kind: Secret
metadata:
  annotations:
    dataflow.argoproj.io/description: |
      This is an example of providing a namespace named Kafka configuration.

      The secret must be named `dataflow-kafka-${name}`.

      # Brokers as a comma-separated list
      brokers: broker.a,broker.b
      # Kafka version
      version: "2.0.0"

      # Enable TLS
      net.tls.caCert: ""
      net.tls.cert: ""
      net.tls.key: ""
      
      # Enable SASL
      net.sasl.mechanism: PLAIN
      net.sasl.user: ""
      net.sasl.password: ""

      [Learn about configuration](../docs/CONFIGURATION.md)
  name: dataflow-kafka-default
stringData:
  brokers: kafka-broker:9092
